"""add match host_nickname

Revision ID: 03aadc0ea567
Revises: eaf3387f70cf
Create Date: 2026-05-16 18:36:14.476645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03aadc0ea567'
down_revision: Union[str, Sequence[str], None] = 'eaf3387f70cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('host_nickname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'host_nickname')
    # ### end Alembic commands ###
