"""add match cancelled

Revision ID: 115ddfb97ef9
Revises: f5684cc3d3a1
Create Date: 2026-05-17 17:08:11.457792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '115ddfb97ef9'
down_revision: Union[str, Sequence[str], None] = 'f5684cc3d3a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('cancelled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'cancelled')
    # ### end Alembic commands ###
