"""add match is_flexible

Revision ID: 2387ba9c46a7
Revises: b62741466c6a
Create Date: 2026-06-01 13:49:57.834861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2387ba9c46a7'
down_revision: Union[str, Sequence[str], None] = 'b62741466c6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('is_flexible', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'is_flexible')
    # ### end Alembic commands ###
