"""drop unused settle columns

Revision ID: 80d0e2e1cd70
Revises: 115ddfb97ef9
Create Date: 2026-05-17 17:51:38.553221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80d0e2e1cd70'
down_revision: Union[str, Sequence[str], None] = '115ddfb97ef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_participants', 'settled')
    op.drop_column('matches', 'host_settled')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('host_settled', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False))
    op.add_column('match_participants', sa.Column('settled', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###
