"""add_game_genre

Revision ID: a2fa425b3a12
Revises: 2387ba9c46a7
Create Date: 2026-06-18 16:51:03.830333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2fa425b3a12'
down_revision: Union[str, Sequence[str], None] = '2387ba9c46a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('genre', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'genre')
    # ### end Alembic commands ###
