"""add settlement flags

Revision ID: c8421807f7ec
Revises: 82802c68095a
Create Date: 2026-05-16 20:21:59.566974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8421807f7ec'
down_revision: Union[str, Sequence[str], None] = '82802c68095a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 기존 row 가 있어서 nullable=False + server_default 필수 (autogenerate 가 빠뜨림).
    op.add_column(
        'match_participants',
        sa.Column('settled', sa.Boolean(), nullable=False, server_default=sa.text('0')),
    )
    op.add_column(
        'matches',
        sa.Column('host_settled', sa.Boolean(), nullable=False, server_default=sa.text('0')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'host_settled')
    op.drop_column('match_participants', 'settled')
    # ### end Alembic commands ###
